ASP_Dotnet/Ex03-SampleMvcFramework/Models/Stock.cs
using SampleMvcFramework.Data;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Security.Policy;
using System.Web;

namespace SampleMvcFramework.Models
{
    public class Stock
    {
        public Stock()
        {
            
        }
        public Stock(int id, string name, string desc, double uPrice)
        {
            StockId = id;
            StockName = name;
            StockDescription = desc;
            UnitPrice = uPrice;
        }

        public void CopyFrom(StockTable table)
        {
            StockId = table.stockId;
            StockName = table.stockName;
            StockDescription = table.stockDescription;
            UnitPrice = table.unitPrice;
        }

        public void CopyTo(Stock stock, StockTable table)
        {
            table.stockId = StockId;
            table.stockName = StockName;
            table.stockDescription = StockDescription;
            table.unitPrice = UnitPrice;
        }
        public int StockId { get; set; }
        public string StockName { get; set; }
        public string StockDescription { get; set; }
        public double UnitPrice { get; set; }


        //We dont want to include html elements inside our C# code. This is against the principle of Seperation of Concerns which was one of the reasons of creating MVC in ASP.NET. 
        //public override string ToString()
        //{
        //    return $"<h1>Stock Name: {StockName}</h1><hr/><p>{StockDescription}</p><p>Unit Price: {UnitPrice}</p>";
        //}
    }
}

ASP_Dotnet/Ex03-SampleMvcFramework/Controllers/HomeController.cs
using SampleMvcFramework.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SampleMvcFramework.Controllers
{
    //All methods inside a controller are called as ACTIONs. Their return value will be an ActionResult which is an abstract class which will be implemented by many classes that return specific results: Json, View, PartialView, RedirectResult and many more. 

    public class HomeController : Controller
    {
        // GET: Home
        public string Index()
        {
            return "Hello World";
        }
        //HTTP is a text based protocol. when a request returns an object. its string representation is returned as RESPONSE. 
        public ViewResult Display()
        {
            var model = new Stock { StockId = 123, StockDescription = "Stock Investments on Infrastructure", StockName = "HDFC Infrastructure Equity Fund", UnitPrice = 13.34545 };
            return View(model); 
            //Every controller will have a method called View that returns a Viewresult. 
        }
    }
}

ASP_Dotnet/Ex03-SampleMvcFramework/Controllers/StocksManagerController.cs
using SampleMvcFramework.Models;
using SampleMvcFramework.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SampleMvcFramework.Controllers
{
    public class StocksManagerController : Controller
    {
        private readonly IStockService stockService;

        //ASp.NET MVC 5 does not come with default DI that we see in .NET CORE. So we can either use 3rd party DI tools like Unity. 
        public StocksManagerController()
        {
            stockService = new StockService(); 
        }
        
        // GET: StocksManager
        public ActionResult Index()
        {
            var data = stockService.GetStocks();
            return View(data);
        }

        //GET called when Add new Hyperlink is clicked
        public ActionResult AddNewStock()
        {
            return View(new Stock());
        }
        //called when submit button in the page is clicked. 
        [HttpPost]
        public ActionResult AddNewStock(Stock postedData)
        {
            stockService.AddStock(postedData);
            return RedirectToAction("Index");
        }

        //Create a View for OnEdit and implement the logic of Posting. 
        public ActionResult OnEdit(int id)
        {
            var stock = stockService.GetStockById(id);
            return View(stock);
        }

        [HttpPost]
        public ActionResult OnEdit(Stock stock)
        {
            stockService.UpdateStock(stock);
            return RedirectToAction("Index");
        }

    }
}

ASP_Dotnet/Ex03-SampleMvcFramework/Views/Home/Display.cshtml
@model SampleMvcFramework.Models.Stock

<h1>Stock Name:@Model.StockName</h1>
<hr />
<p>@Model.StockDescription</p>
<p>Unit Price: @Model.UnitPrice</p>

ASP_Dotnet/Ex03-SampleMvcFramework/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar">Home</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("MVC Training", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
                @Html.ActionLink("All Stocks", "Index", "StocksManager", new { area = "" }, htmlAttributes:
new { @class = "btn btn-warning" })
                @Html.ActionLink("Add New", "AddNewStock", "StocksManager", new { area = "" }, htmlAttributes:
new { @class = "btn btn-info" })
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>Powered by ASP.NET MVC, &copy; @DateTime.Now.Year - Fnf ASP.NET MVC Training</p>
        </footer>
    </div>

    
</body>
</html>

ASP_Dotnet/Ex03-SampleMvcFramework/Views/StocksManager/AddNewStock.cshtml
@model SampleMvcFramework.Models.Stock

@{
    ViewBag.Title = "AddNewStock";
}

<h2>AddNewStock</h2>
@using (Html.BeginForm())
{
    <div>
        <p>
            @Html.LabelFor(m => m.StockName)
            @Html.EditorFor(m => m.StockName, new { htmlAttributes = new { @class = "form-control" } })
        </p>
        <p>
            Enter the Stock Description:
            @Html.EditorFor(m => m.StockDescription, new { htmlAttributes = new { @class = "form-control" } })
        </p>
        <p>
            Enter the Stock Price:
            @Html.EditorFor(m => m.UnitPrice, new { htmlAttributes = new { @class = "form-control" } })
        </p>
        <button type="submit" class="btn btn-info">Save Changes</button>
    </div>
}


ASP_Dotnet/Ex03-SampleMvcFramework/Views/StocksManager/Index.cshtml
@model List<SampleMvcFramework.Models.Stock>
@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>
@Html.ActionLink("Add New Stock", "AddNewStock", new {}, new { @class = "btn btn-info"})
<hr />
<div>
    <table class="table table-bordered table-striped">
        <thead>
            <tr>
                <th>StockId</th>
                <th>Stock Name</th>
                <th>Stock Description</th>
                <th>Unit Price</th>
                <th>Options</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var stock in Model)
            {
                <tr>
                    <td>@stock.StockId</td>
                    <td>@stock.StockName</td>
                    <td>@stock.StockDescription</td>
                    <td>@stock.UnitPrice</td>
                    <td>
                        @Html.ActionLink("Edit"/*Text to Display*/, "OnEdit"/*Action in the Controller*/, new { id = stock.StockId }/*value for the id*/, new { @class = "btn btn-primary" })
                        @Html.ActionLink("Delete"/*Text to Display*/, "OnDelete"/*Action in the Controller*/, new { id = stock.StockId }/*value for the id*/, new { @class = "btn btn-danger" })
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>


ASP_Dotnet/Ex03-SampleMvcFramework/Views/StocksManager/OnEdit.cshtml
@model SampleMvcFramework.Models.Stock

@{
    ViewBag.Title = "OnEdit";
}

<h2>OnEdit</h2>
<hr />
@using (Html.BeginForm())
{
    //Helper function that provides the editors for all the properties.
    @*@Html.EditorForModel()*@

    <p>
        Stock Id: @Html.DisplayFor(m => m.StockId)
        @Html.HiddenFor(m=>m.StockId)
    </p>
    <p>
        Stock Name: @Html.EditorFor(m => m.StockName, new { htmlAttributes = new { @class = "form-control" } })
    </p>
    <p>
        Stock Desc: @Html.EditorFor(m => m.StockDescription, new { htmlAttributes = new { @class = "form-control" } })
    </p>
    <p>
        Stock Price: @Html.EditorFor(m => m.UnitPrice, new { htmlAttributes = new { @class = "form-control" } })
    </p>
    <input type="submit" class="btn btn-danger" value="Update" />
}